#!/bin/bash

#set -e

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT

# direct all logs to after-install.log
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/home/ubuntu/quick-translates-api-worker/scripts/logging/after-install.log 2>&1

QT_DIR="/home/ubuntu/quick-translates-api-worker"
QT_ENV_DIR="/home/ubuntu/quick-translates-api-worker-env"
SOURCE="/home/ubuntu/models"
DESTINATION="${QT_DIR}/data"
LINK="${DESTINATION}/models"

aws s3 cp s3://quick-translates-env/.env ${QT_DIR}

# changing ownership of folder
sudo chown -R ubuntu:www-data ${QT_DIR}

# change file permissions to -rw-r--r--
sudo find ${QT_DIR} -type f -exec chmod 644 {} \;

# change directory permissions to drwxr-xr-x
sudo find ${QT_DIR} -type d -exec chmod 755 {} \;

# make whisper executable
chmod +x ${QT_DIR}/whisper/generate_transcript.sh ${QT_DIR}/whisper/generate_transcript_c.sh

# activate virtual env
source ${QT_ENV_DIR}/bin/activate

# install dependencies
${QT_ENV_DIR}/bin/pip install -r ${QT_DIR}/requirements/production.txt


if [ ! -L "$LINK" ]; then
  ln -s "$SOURCE" "$DESTINATION"
  echo "Symbolic link created: $SOURCE -> $DESTINATION"
else
  echo "Symbolic link $LINK already exists."
fi

