#!/bin/bash

#set -e

# keep track of the last executed command
trap 'last_command=$current_command; current_command=$BASH_COMMAND' DEBUG
# echo an error message before exiting
trap 'echo "\"${last_command}\" command filed with exit code $?."' EXIT

# direct all logs to application-start.log
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>/home/ubuntu/quick-translates-api-worker/scripts/logging/application-start.log 2>&1

SOURCE="/home/ubuntu/models"
DESTINATION="/home/ubuntu/quick-translates-api-worker/data"
LINK="/home/ubuntu/quick-translates-api-worker/data/models"

if [ ! -L "$LINK" ]; then
  ln -s "$SOURCE" "$DESTINATION"
  echo "Symbolic link created: $SOURCE -> $DESTINATION"
else
  echo "Symbolic link $LINK already exists."
fi

systemctl restart quick-translates.service
systemctl restart nginx.service